/*CONSULTA PARA COBRO DE APORTACIONES*/

SELECT "AHO_CODIGO_COO", "AHO_CODIGO_CTA", CAST((AHO_CANT_AHORRO+(AHO_CANT_AHORRO/2)) AS DECIMAL(12,2)) as 'TotalAportaciones' FROM "DBA"."AHORROS" WHERE AHO_CODIGO_CTA IN (SELECT SOC_CUENTA FROM "DBA"."Socios_Planilla" where SOC_PATRONO = 10000005 and SOC_SOCIO = 7786 and SOC_FECHA = '2023-03-23' AND SOC_APORTACION > 0)

/*CONSULTA PARA COBRO DE CREDITOS*/

SELECT CRE_CODIGO_CTA,(CRE_MTO_ORIGINAL/(CRE_PLAZO_MESES*2))*3
FROM DBA.CREDITOS
WHERE CRE_CODIGO_CTA IN (SELECT SOC_CUENTA FROM "DBA"."Socios_Planilla"
where SOC_PATRONO = 10000005 and SOC_SOCIO = 7782 and SOC_FECHA = '2023-03-23' AND SOC_CAPITAL > 0)


/*COBRO INTERESES*/
SELECT "CRE_CODIGO_COOP", "CRE_CODIGO_CTA",CAST((("CRE_MTO_ORIGINAL"/("CRE_PLAZO_MESES"*2))*3) AS DECIMAL(12,2)) AS 'CAPITAL', CAST(((("CRE_SALDO"*("CRE_PORC_INTERES"/100))/12)/2) AS DECIMAL(12,2))+CAST(((((("CRE_SALDO"-(("CRE_MTO_ORIGINAL"/("CRE_PLAZO_MESES"*2))*3)*("CRE_PORC_INTERES"/100/12/2))+("CRE_MTO_ORIGINAL"/("CRE_PLAZO_MESES"*2)))*("CRE_PORC_INTERES"/100))/12)) AS DECIMAL(12,2)) AS 'TOTAL INTERESES' FROM "DBA"."CREDITOS" WHERE "CRE_CODIGO_CTA" IN (SELECT "SOC_CUENTA" FROM "DBA"."Socios_Planilla" where "SOC_PATRONO" = 10000005 and "SOC_SOCIO" = 7784 and "SOC_FECHA" = '2023-03-23' AND "SOC_CAPITAL" > 0) 